// Generated by prefgen.py - Do not edit by hand!

package org.sufficientlysecure.ical.ui;

import android.content.SharedPreferences;

import org.sufficientlysecure.ical.Settings;

public class SettingsActivityBase extends android.preference.PreferenceActivity
        implements SharedPreferences.OnSharedPreferenceChangeListener {

    public SettingsActivityBase() {
        super();
    }

    @Override
    protected void onCreate(android.os.Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(org.sufficientlysecure.ical.R.xml.settings);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences p, String key) {
        updatePreferenceText(key);
    }

    protected SharedPreferences getPreferences() {
        return getPreferenceScreen().getSharedPreferences();
    }

    protected String createPreferenceText(int id, CharSequence choice) {
        return getResources().getString(id) + " (" + choice + ")";
    }

    protected void updatePreferenceText(String key) {
        android.preference.Preference p = findPreference(key);
        int resId;
        if (p instanceof android.preference.ListPreference) {
            switch (key) {
                case Settings.PREF_DUPLICATE_HANDLING:
                    resId = org.sufficientlysecure.ical.R.string.how_to_handle_duplicate_events;
                    break;
                default:
                    return;
            }
            CharSequence choice = ((android.preference.ListPreference) p).getEntry();
            p.setSummary(createPreferenceText(resId, choice));
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        getPreferences().registerOnSharedPreferenceChangeListener(this);
        updatePreferenceText(Settings.PREF_DUPLICATE_HANDLING);
    }
    @Override
    protected void onPause() {
        super.onPause();
        getPreferences().unregisterOnSharedPreferenceChangeListener(this);
    }
}
