= iCal Import/Export Settings

This document describes the settings for iCal Import/Export.

== Introduction

Settings can be reached from the overflow menu on the top right of the screen.
If you are using a very old version of Android, you may need to press the
menu button on your device to bring up the menu containing the settings.

=== General

These settings control general application behaviour.

==== Save passwords (Y/N)

Store user entered passwords in insecure local storage.

When you enter a password for importing from a URL, this setting controls
whether the password will be saved so that you can avoid re-typing it
when you next choose import a URL again. Please note that the password is
_not_ encrypted and so on a compromised or rooted device the password
could be stolen. *Enable with care*.

=== Import

These settings apply only when importing iCalendar files. You may wish
to change the defaults in order to have finer control over the calendar
contents in the imported result.

==== Ignore duplicates (Y/N)

Ignore entries that are already in the destination calendar.

:defaultValue: true

==== Keep UIDs (Y/N)

Use any existing unique identifiers to identify and find duplicate events.

:defaultValue: true

=== Reminders

These settings allow you to change the reminders that will be created
for events that have been imported.

==== Import reminders (Y/N)

Use reminders from the imported file instead of default reminders when present.

:defaultValue: true

==== Default reminders

Choose the reminders to apply to imported events.

:type: org.sufficientlysecure.ical.ui.RemindersDialog
:dialogLayout: @layout/reminders

=== Compatibility

These settings concern the parsing of iCalendar files. You may wish to change
these if your file is not parsed correctly or gives errors when parsed.

==== Allow different line endings (Y/N)

Support various line wrapping schemes used by different products.

:defaultValue: true
:key: ical4j.unfolding.relaxed

==== Permissive parsing (Y/N)

Support various incorrect but common iCalendar file quirks.

:defaultValue: true
:key: ical4j.parsing.relaxed

==== Microsoft compatible (Y/N)

Support calendars exported by Microsoft&#174; Outlook&#174; and Microsoft&#174; Exchange&#8482;.

:defaultValue: true
:key: ical4j.compatibility.outlook

==== Notes compatible (Y/N)

Support calendars exported by IBM&#174; Notes&#174; (Formerly Lotus Notes&#174;).

:defaultValue: true
:key: ical4j.compatibility.notes

==== vCard compatible (Y/N)

Support events in vCard format.

:key: ical4j.compatibility.vcard

=== Export

These settings are used when exporting a calendar from your device to an
iCalendar file.

==== Permissive export (Y/N)

Skip extensive validation of the output file when exporting calendars.

:defaultValue: true
:key: ical4j.validation.relaxed

///////////////////////////////////////////
The following keys are used internally only
:key: lastExportFile
:key: lastUrl
:key: lastUrlUsername
:key: lastUrlPassword
///////////////////////////////////////////
