= iCal Import/Export Settings

This document describes the settings for iCal Import/Export.

== Introduction

Settings can be reached from the overflow menu on the top right of the screen.
If you are using a very old version of Android, you may need to press the
menu button on your device to bring up the menu containing the settings.

=== General

These settings control general application behaviour.

==== Save passwords (Y/N)

Save passwords in insecure local storage/Do not save passwords.

Whether to store user entered passwords in insecure local storage. When
you enter a password for importing from a URL, this setting controls
whether the password will be saved so that you can avoid re-typing it
when you next choose to import a URL again.

WARNING: The password is _not_ encrypted and so on a compromised or rooted
device the password could be stolen. *Enable only with care*.

==== Timezone Updates (Y/N)

Update timezone data over the network/Do not update timezone data.

:key: net.fortuna.ical4j.timezone.update.enabled

When enabled, timezone updates will be requested on demand
from http://tzurl.org/. Unless timezones that you use have recently
changed this is most likely not required. Even if your timezone has
changed, most aqpplications ignore all timezone information in iCalendar
files except for the name.

=== Import

These settings apply only when importing iCalendar files. You may wish
to change the defaults in order to have finer control over the calendar
contents in the imported result.

==== Duplicate handling

How to handle duplicate events while importing.

* Replace with the imported event if in the same calendar (default)
* Replace with the imported event regardless of calendar
* Keep the existing event and ignore the imported event
* Don't check for duplicates at all, always insert all imported events

:enumValues: DUP_REPLACE, DUP_REPLACE_ANY, DUP_IGNORE, DUP_DONT_CHECK

Importing will be slightly faster if you do not check for duplicates. Note
that UID handling as described below will affect how duplicates are
identified. In the event that "Global UIDs" below is _disabled_, the choice
"Replace with the imported event regardless of calendar" is equivalent to
the default first option, since this means that only UIDs within the
destination calendar will be considered as duplicates.

==== Keep UIDs (Y/N)

Import unique identifiers to identify events/Generate new identifiers for
imported events.

:defaultValue: true

Enabling this setting means that if you import the same event multiple
times, it will be correctly identified as a duplicate even if it has been
renamed, moved in time or otherwise edited. When this option is not enabled
duplicates are detected using a heuristic which can fail.

==== Global UIDs (Y/N)

Identifiers are globally unique/Identifiers are unique only within a calendar.

This setting identifies imported entries by their unique id regardless of
which calendar they are in. This should be enabled if you wish to ensure
that events are globally unique by their id, i.e. that a given imported
event can only be in one calendar at once.

=== Reminders

These settings allow you to change the reminders that will be created
for events that have been imported.

==== Import reminders (Y/N)

Import reminders/Do not import reminders.

:defaultValue: true

When this setting is false, and when no reminder is associated with an
event, the default reminders specified below will be used instead. If
You do not want any reminders to be created at all, set this to false
and remove any reminders from the default reminders.

NOTE: Not all types of reminders are supported. Only supported types
will be imported.

==== Default reminders

Choose the reminders to apply to imported events.

:type: org.sufficientlysecure.ical.ui.RemindersDialog
:dialogLayout: @layout/reminders

This dialog allows a selection of reminders to be created for each
event. These default reminders will only be used when "Import Reminders"
is false or if no reminder is associated with an event.

=== Compatibility

These settings concern the parsing of iCalendar files. You may wish to change
these if your file is not parsed correctly or gives errors when importing.

==== Allow different line endings (Y/N)

Allow various line wrapping schemes/Enforce RFC compliant line wrapping.

:defaultValue: true
:key: ical4j.unfolding.relaxed

This setting should always be enabled unless you wish to test whether
a given iCalendar file adheres to the iCalendar specification.

==== Permissive parsing (Y/N)

Support common incorrect quirks/Enforce RFC compliant input.

:defaultValue: true
:key: ical4j.parsing.relaxed

You should typically leave this setting enabled since the most common
sources of iCalendar files usually require it.

==== Microsoft compatible (Y/N)

Support calendars exported by Outlook&#174; and Exchange&#8482;/No
Microsoft&#174; calendar support.

:defaultValue: true
:key: ical4j.compatibility.outlook

Although this setting should allow Microsoft calendars to be read, it is
possible if not likely that some advanced or bespoke features may not be
imported.

==== Notes compatible (Y/N)

Support calendars exported by IBM&#174; (Formerly Lotus) Notes&#174;/
No Notes&#174; calendar support.

:defaultValue: true
:key: ical4j.compatibility.notes

==== vCard compatible (Y/N)

Support events in vCard format/No vCard support.

:key: ical4j.compatibility.vcard

=== Export

These settings are used when exporting a calendar from your device to an
iCalendar file.

==== Permissive export (Y/N)

Skip extensive validation of the output file/Validate the output file.

:defaultValue: true
:key: ical4j.validation.relaxed

This setting does not disable all validation. The iCal4j library used
for writing calendars will reject gratuitous errors such as missing
mandatory elements. These can occur when the Android calendar being exported
is corrupt, for example.

==== Microsoft extensions (Y/N)

Add Outlook&#174; and Exchange&#8482; extensions to exported calendars/No
Microsoft&#174; calendar extensions.

:defaultValue: true

=== Developer tools

These settings are for developers of the application only. They will not
typically be useful for users. You may be asked to enable one or more of
these settings in order to help the developers fix a bug you have reported.

==== Developer mode (Y/N)

Enable developer features/Disabled.

==== Debug logging (Y/N)

Extra logging for debugging/Disabled.

When enabled, more information will be logged about the actions of the
application while it runs.

:dependency: developer_mode

==== Test file support (Y/N)

Process test file directives/Disabled.

:dependency: developer_mode


///////////////////////////////////////////
The following keys are used internally only
:key: uidPid
:key: lastExportFile
:key: lastUrl
:key: lastUrlUsername
:key: lastUrlPassword
///////////////////////////////////////////
