// Generated by prefgen.py - Do not edit by hand!

package org.sufficientlysecure.ical.ui;

import android.content.SharedPreferences;

public class SettingsActivityBase extends android.preference.PreferenceActivity
        implements SharedPreferences.OnSharedPreferenceChangeListener {

    public SettingsActivityBase() {
        super();
    }

    @Override
    protected void onCreate(android.os.Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(org.sufficientlysecure.ical.R.xml.settings);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences p, String k) { }

    protected SharedPreferences getPreferences() {
        return getPreferenceScreen().getSharedPreferences();
    }

    @Override
    protected void onResume() {
        super.onResume();
        getPreferences().registerOnSharedPreferenceChangeListener(this);
    }
    @Override
    protected void onPause() {
        super.onPause();
        getPreferences().unregisterOnSharedPreferenceChangeListener(this);
    }
}
